---
title: "A study of the skewed generalized t-distribution"
output: html_document
date: "2024-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ifft)
library(sgt)
```


```{r include=FALSE, eval=FALSE}
num_simulations <- 1000
num_paths <- 10000
num_periods <- 20
params <- c(0.08, 0.12, 3.18, 0.02)

#####################################

pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                     max = num_simulations, # Maximum value of the progress bar
                     style = 3,    # Progress bar style (also available style = 1 and style = 2)
                     width = 50,   # Progress bar width. Defaults to getOption("width")
                     char = "=")   # Character used to create the bar

params_for_sums <- data.frame(m = numeric(0), s =  numeric(0), nu = numeric(0), xi = numeric(0))
suppressWarnings({
  for(i in 1:num_simulations) {
    x_sstd_mat <- replicate(num_paths, rsstd(num_periods, mean = params[1], sd = params[2], nu = params[3], xi = params[4]))
    x_sstd_sums <- apply(x_sstd_mat, 2, sum)
    
    loglik_sstd <- function(beta, x) {sum(- dsstd(x, mean = beta[1], sd = beta[2], nu = beta[3], xi = beta[4], log = TRUE))}
    start <-  c(mean(x_sstd_sums), sd(x_sstd_sums), 3, 1)
    params_for_sums[i, ] <-  optim(start, loglik_sstd, x = x_sstd_sums)$par
    setTxtProgressBar(pb, i)
  }
})

saveRDS(params_for_sums, file="params_for_sums.RData")
```
```{r}
loadRDS(params_for_sums, file="params_for_sums.RData")
```


```{r include=FALSE, eval=FALSE}
params_for_sums_means <- as.data.frame(lapply(
  params_for_sums,
  mean
))

params_for_sums_sd <- as.data.frame(lapply(
  params_for_sums,
  sd
))

params_for_sums_summary <- rbind(params_for_sums_means, params_for_sums_sd)
rownames(params_for_sums_summary) <- c("m", "s")

saveRDS(params_for_sums_summary, file="params_for_sums_summary.RData")
```

 	  m 	    s 	        nu 	      xi
m 	1.605 	7060.920 	  320.586 	0.02
s 	0.005 	85.209 	    67.491 	  0.14

```{r}
loadRDS(params_for_sums_summary, file="params_for_sums_summary.RData")
knitr::kable(params_for_sums_summary, digits = 3)
```



```{r include=FALSE, eval=FALSE}
num_simulations <- 100
num_paths <- 10000
num_periods <- 20
params <- c(0.08, 0.12, 3.18, 0.02)

#####################################

pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                     max = num_simulations, # Maximum value of the progress bar
                     style = 3,    # Progress bar style (also available style = 1 and style = 2)
                     width = 50,   # Progress bar width. Defaults to getOption("width")
                     char = "=")   # Character used to create the bar

loglik_sstd = function(beta, x) {sum(- dsstd(x, mean = beta[1], sd = beta[2], nu = beta[3], xi = beta[4], log = TRUE))}

m_for_sums <- matrix(numeric(num_periods * num_simulations), num_periods, num_simulations)
s_for_sums <- matrix(numeric(num_periods * num_simulations), num_periods, num_simulations)
nu_for_sums <- matrix(numeric(num_periods * num_simulations), num_periods, num_simulations)
xi_for_sums <- matrix(numeric(num_periods * num_simulations), num_periods, num_simulations)
suppressWarnings({
  for(i in 1:num_simulations) {
    sstd_sums_mat <- replicate(num_paths, cumsum(rsstd(num_periods, mean = params[1], sd = params[2], nu = params[3], xi = params[4])))
    for(j in 1:num_periods) {
      start <-  c(mean(sstd_sums_mat[j, ]), sd(sstd_sums_mat[j, ]), 3, 1)
      hat_params <-  optim(start, loglik_sstd, x = sstd_sums_mat[j, ])$par
      m_for_sums[j, i] <- hat_params[1]
      s_for_sums[j, i] <- hat_params[2]
      nu_for_sums[j, i] <- hat_params[3]
      xi_for_sums[j, i] <- hat_params[4]
    }
    setTxtProgressBar(pb, i)
  }
})
```






```{r include=FALSE, eval=FALSE}
params_for_cum_sums_m_means <- as.data.frame(apply(
  m_for_sums,
  1,
  mean
))

params_for_cum_sums_m_sd <- as.data.frame(apply(
  m_for_sums,
  1,
  sd
))

params_for_cum_sums_s_means <- as.data.frame(apply(
  s_for_sums,
  1,
  mean
))

params_for_cum_sums_s_sd <- as.data.frame(apply(
  s_for_sums,
  1,
  sd
))

params_for_cum_sums_nu_means <- as.data.frame(apply(
  nu_for_sums,
  1,
  mean
))

params_for_cum_sums_nu_sd <- as.data.frame(apply(
  nu_for_sums,
  1,
  sd
))

params_for_cum_sums_xi_means <- as.data.frame(apply(
  xi_for_sums,
  1,
  mean
))

params_for_cum_sums_xi_sd <- as.data.frame(apply(
  xi_for_sums,
  1,
  sd
))

params_for_cum_sums_summary <- cbind(
  params_for_cum_sums_m_means, 
  params_for_cum_sums_m_sd,
  params_for_cum_sums_m_means - 1.96 * params_for_cum_sums_m_sd,
  params_for_cum_sums_m_means + 1.96 * params_for_cum_sums_m_sd,
  params_for_cum_sums_s_means, 
  params_for_cum_sums_s_sd,
  params_for_cum_sums_s_means - 1.96 * params_for_cum_sums_s_sd,
  params_for_cum_sums_s_means + 1.96 * params_for_cum_sums_s_sd,
  params_for_cum_sums_nu_means,
  params_for_cum_sums_nu_sd,
  params_for_cum_sums_nu_means - 1.96 * params_for_cum_sums_nu_sd,
  params_for_cum_sums_nu_means + 1.96 * params_for_cum_sums_nu_sd,
  params_for_cum_sums_xi_means,
  params_for_cum_sums_xi_sd,
  params_for_cum_sums_xi_means - 1.96 * params_for_cum_sums_xi_sd,
  params_for_cum_sums_xi_means + 1.96 * params_for_cum_sums_xi_sd
)

colnames(params_for_cum_sums_summary) <- c(
  "m_mean",
  "m_sd",
  "m_ci_l",
  "m_ci_u",
  "s_mean",
  "s_sd",
  "s_ci_l",
  "s_ci_u",
  "nu_mean",
  "nu_sd",
  "nu_ci_l",
  "nu_ci_u",
  "xi_mean",
  "xi_sd",
  "xi_ci_l",
  "xi_ci_u"
)

saveRDS(params_for_cum_sums_summary, file="params_for_cum_sums_summary.RData")
```

```{r}
loadRDS(params_for_cum_sums_summary, file="params_for_cum_sums_summary.RData")
```

```{r}
ggplot(params_for_cum_sums_summary, aes(x = 1:20, y = m_mean)) +
  geom_ribbon(
      mapping = aes(
        ymin = m_ci_l, 
        ymax = m_ci_u
      ), fill = "gray") +
  geom_line() +
  labs(title = "Means of simulations of m-parameter for skewed t", subtitle = "95% c.i.", x = "time", y = "mean m")
```
This looks like:

$$m(n) = n \cdot m(0)$$

```{r}
formula_m <- data.frame(m_n = 1:20 * params[1])
m_n <- params_for_cum_sums_summary$m_mean
compare_m_n <- t(cbind(formula_m, m_n))
rownames(compare_m_n) <- c("formula", "m_n")
knitr::kable(compare_m_n, digits = 3)
```
```{r}
plot(1:20, compare_m_n[1, ], type = "l", col = "red", xlab = "time", ylab = "mean m", lwd = 3)
lines(compare_m_n[2, ], col = "green", lwd = 1.5, lty = 2)
legend("topleft", c("formula", "m_n"), col = c("red", "green"), lty = c(1, 2), lwd = c(3, 1.5))
```


```{r}
ggplot(params_for_cum_sums_summary, aes(x = 1:20, y = s_mean)) +
  geom_ribbon(
      mapping = aes(
        ymin = s_ci_l, 
        ymax = s_ci_u
      ), fill = "gray") +
  geom_line() +
  labs(title = "Means of simulations of s-parameter for skewed t", subtitle = "95% c.i.", x = "time", y = "mean s")
```
This looks like:

$$s(n) = \sqrt{n s(1)^2}$$

```{r}
formula_s <- data.frame(s_n = sqrt(1:20 * params[2]^2))
s_n <- params_for_cum_sums_summary$s_mean
compare_s_n <- t(cbind(formula_s, s_n))
rownames(compare_s_n) <- c("formula", "s_n")
knitr::kable(compare_s_n, digits = 3)
```

```{r}
plot(1:20, compare_s_n[1, ], type = "l", col = "red", xlab = "time", ylab = "mean s")
lines(compare_s_n[2, ], col = "green")
legend("topleft", c("formula", "s_n"), col = c("red", "green"), lty = 1)
```




```{r}
ggplot(params_for_cum_sums_summary, aes(x = 1:20, y = nu_mean)) +
  geom_ribbon(
      mapping = aes(
        ymin = nu_ci_l, 
        ymax = nu_ci_u
      ), fill = "gray") +
  geom_line() +
  labs(title = "Means of simulations of nu-parameter for skewed t", subtitle = "95% c.i.", x = "time", y = "mean nu")
```

We don't have a good guess here:

```{r}
formula_nu <- data.frame(nu_n = (1:20 * params[4]^4)^(-4))
nu_n <- params_for_cum_sums_summary$nu_mean
compare_nu_n <- t(cbind(formula_nu, nu_n))
rownames(compare_nu_n) <- c("formula", "nu_n")
knitr::kable(compare_nu_n, digits = 3)
```

```{r}
plot(1:20, compare_nu_n[1, ], type = "l", col = "red", xlab = "time", ylab = "mean nu")
lines(compare_nu_n[2, ], col = "green")
legend("topleft", c("formula", "nu_n"), col = c("red", "green"), lty = 1)
```

```{r}
ggplot(params_for_cum_sums_summary, aes(x = 1:20, y = xi_mean)) +
  geom_ribbon(
      mapping = aes(
        ymin = xi_ci_l, 
        ymax = xi_ci_u
      ), fill = "gray") +
  geom_line() +
  labs(title = "Means of simulations of xi-parameter for skewed t", subtitle = "95% c.i.", x = "time", y = "mean xi")
```

Again, no good guess:
```{r}
formula_xi <- data.frame(xi_n = (1:20 * params[3]^3)^(-3))
xi_n <- params_for_cum_sums_summary$xi_mean
compare_xi_n <- t(cbind(formula_xi, xi_n))
rownames(compare_xi_n) <- c("formula", "xi_n")
knitr::kable(compare_xi_n, digits = 3)
```

```{r}
plot(1:20, compare_xi_n[1, ], type = "l", col = "red", xlab = "time", ylab = "mean xi", ylim = c(0, max(c(compare_xi_n[1, ], compare_xi_n[2, ]))))
lines(compare_xi_n[2, ], col = "green")
legend("topleft", c("formula", "xi_n"), col = c("red", "green"), lty = 1)
```
