---
title: "Wittgenstein's Ruler"
output: html_document
date: "2024-05-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fGarch)
```


```{r}
# Define the survival functions
calculate_normal_dist <- function(x, params = c(0, 1)) {pnorm(x, mean = params[1], sd = params[2])}
calculate_t_dist <- function(x, params = c(0, 1, 3, 1)) {psstd(x, mean = params[1], sd = params[2], nu = params[3], xi = params[4])}
calculate_normal_survival <- function(x, params = c(0, 1)) {1 - calculate_normal_dist(x, params)}
calculate_t_survival <- function(x, params = c(0, 1, 3, 1)) {1 - calculate_t_dist(x, params)}

## Probability of distribution being Gaussian rather than skewed t conditional 
## on event x
## mode = "min": Calculate conditional probability for smallest observed value or less
## mode = "max": Calculate conditional probability for largest observed value or more
bayes_survival <- function(p_gaussian, x, norm_params, sstd_params, mode = "min") {

    if(mode == "min") {
      normal_survival <- calculate_normal_dist(x, norm_params)
      t_survival <- calculate_t_dist(x, sstd_params)
    } else {
      normal_survival <- calculate_normal_survival(x, norm_params)
      t_survival <- calculate_t_survival(x, sstd_params)
    }
  
    # Calculating the conditional probabilities using Bayes' theorem
    numerator = normal_survival * p_gaussian
    denominator = (t_survival * (1 - p_gaussian)) + (normal_survival * p_gaussian)
    
    # Returning the probability P[gaussian | event]
    p_event_given_gaussian = numerator / denominator
    
    list(
      p_gaussian = p_gaussian,
      conditional_probability = p_event_given_gaussian
    )
}
```

```{r}
x <- min(data_df[[1]])

# Defining the different probabilities for P[gaussian]
p_gaussian_values <- 1 - 10^(-(seq(0, 6, length.out = 100)))
par(mfrow = c(2, 4))
lapply(
  seq_along(data_df),
  function(i) {
    probs <- bayes_survival(
      p_gaussian_values, 
      min(data_df[[i]]),
      fits_norm[[1]],
      c(fits[[1]]$m, fits[[1]]$s, fits[[1]]$nu, fits[[1]]$xi),
      mode = "min"
    )
    plot(p_gaussian_values, probs[[2]], pch = 16, cex = 0.3, 
         xlab = "P[Gauss]", ylab = "P[Gauss | event]",
         main = fund_names[i]
    )
    abline(0, 1, col = "red")
  }
)
par(mfrow = c(1, 1))
```


```{r}
x <- max(data_df[[1]])

# Defining the different probabilities for P[gaussian]
p_gaussian_values <- c(0.5, 0.999, 0.9999, 0.99999, 0.999999, 1)

## P[X < x]
out <- bayes_survival(
  p_gaussian_values, 
  x,
  fits_norm[[1]],
  c(fits[[1]]$m, fits[[1]]$s, fits[[1]]$nu, fits[[1]]$xi)
)
out
```



```{r}
# Create and print the table
table_results <- 1 - sapply(p_gaussian_values, bayes_survival, simplify = FALSE, x = x)

# Convert to dataframe for pretty printing
table_df <- do.call(rbind.data.frame, table_results)

# Print the table
print(table_df)
```



